### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '2002FemResp.dct',,   '2006_2010_FemPregSetup.dct'

### ISSUE THREAD

**Issue by Aadilji** [AllenDowney/ThinkStats2#186]
sir, i purchased ur book day before yesterday,
As soon as i m running the file nsfg2.py it gives me error

FileNotFoundError: [Errno 2] No such file or directory: '2006_2010_FemPregSetup.dct'

And when i run nsgf.py it gives me error

FileNotFoundError: [Errno 2] No such file or directory: '2002FemResp.dct'

pls resolve this issue

**Comment by Aadilji** [comment]
just run the nsfg.py in ANACONDA, it will give all tests pass

**Comment by DanielPantie** [comment]
Issue: I had the same issue when running the very first code (nsfg), i.e., FileNotFoundError for '2002FemResp.dct' and '2002FemPreg.dct' files.
Background: Allen's repository has these files in ThinkStats2-master/code (at least that's how it's downloaded in my desktop), while the book says the files are in ThinkStats2/code.
Solution: move folder 'code' into ThinkStats2-master/thinkstats2, which means that those two files will now be in ThinkStats2-master/thinkstats2/code

This issue got me stuck on my first day reading the book (yesterday, Sept 12) and nothing worked until I had the idea of moving the code. I was going to give up if this had failed and would have wasted 31€. Let's see if there are no more (major) issues.

**Comment by AllenDowney** [comment]
Sorry, I know that working with the data and code can be frustrating! For the second edition, I recommend running the Jupyter notebooks on Colab. There are links to the notebooks here:

https://allendowney.github.io/ThinkStats2/

I hope that helps!

**Comment by DanielPantie** [comment]
Thank you for your reply. I will try Jupyter. I never used it and I am new
to python.

**Comment by DanielPantie** [comment]
Seems like preg() in colab is the equivalent of df (=DataFrame) in python?
Instead of df.columns it should be preg.columns. If I am right, how much
Colab differs from the desktop version of python. Because if it's too much,
I may not opt for it as it could impact my learning schedule.

I execute your code in Colab and it returns errors only (see below
example). It's my first time using Colab, so it might be my fault. I simply
opened the github link you sent and ran the code.

[image: image.png]

Also no success when I ran the code on my desktop. It was successful the
first time, after more attempts this is what I get.

[image: image.png]

Also, I try to run >>>df.columns, which I type print(df.columns), and
nothing happens.

I am really interested in engaging with Colab, but nothing works in my
first steps with the book. Not in Colab nor in the desktop version. It
impacts all my learning plans. Please help me to progress with the book.
All I need is to learn how to code statistics with python.

Thank you. Regards.

**Comment by AllenDowney** [comment]
Here's a link to the first notebook on Colab

https://colab.research.google.com/github/AllenDowney/ThinkStats2/blob/master/code/chap01ex.ipynb

If you open it and select "Run All", it should run all the cells without producing any errors. And there are some empty cells where you can work on the notebooks.

**Comment by DanielPantie** [comment]
Thank you. It works! My problem is that I was running one line at a time
and starting from line 24. However, I will put your book aside and learn
differently. I hope it will be possible to follow your 3rd edition without
your intervention, be it in Colab, Anaconda, desktop python, etc. Good luck!

I have just ordered this book with plenty of exercises and real world data.
I will use chat GPT to provide the python code of the exercises, learn,
adjust where necessary and move on. I hope at the end of 1/3 of the book
I'll need chatGPT only for consultation/comparison. My problem is not
statistics, it's coding.
https://www.amazon.com/Introduction-Econometrics-Global-James-Stock/dp/1292264454

I know this book very well, I used it in my master program over a decade
ago. I still have the book, but the data is no longer available.
