### ISSUE TITLE
Modular latex source

### ISSUE THREAD

**Issue by tobanw** [AllenDowney/ThinkStats2#39]
A useful way to structure latex documents is to use the `\input{}` or `\include{}` commands to make a [modular document](https://en.wikibooks.org/wiki/LaTeX/Modular_Documents). This would be a nice way to separate chapters in the latex source.

**Comment by AllenDowney** [comment]
This is a recurring suggestion, but I have never understood why.

I do a HUGE amount of searching and search/replace in order to check
consistency, find the first definition of something, find all uses of a
vocab word, find labels for cross-references, and on and on.  All of those
things would be a royal pain if I split it up.

And I don't see any advantage in splitting it up.  Is there one?

**Comment by tobanw** [comment]
It just makes the source code more organized. I don't have a strong reason to favor it, so feel free to close this issue if you don't want to change your workflow.

However, your search/replace problem has solutions. For example, in Atom you can do Ctrl+Shift+f to search across all project files. Vim can run commands across buffers. I'm not sure about other editors, but would be surprised if you couldn't get it for any reasonable programming-friendly editor.

**Comment by AllenDowney** [comment]
Ok, thanks anyway for the suggestion.
